# Stage 1 - Build React app
FROM node:18-alpine AS build

WORKDIR /app

# Copy only package files first
COPY frontend/package*.json ./

# Install dependencies inside container
RUN npm install

# Copy rest of frontend source code
COPY frontend .

# Build production app
RUN npm run build


# Stage 2 - Serve with nginx
FROM nginx:alpine

COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
